/**
 * Frozen snapshot of the catalogue as it was first migrated into Supabase.
 *
 * This is the disaster-recovery copy for `scripts/seed-supabase.ts`. It is
 * plain data with NO imports on purpose: `content/schemas.ts` has since gained
 * required fields (`batteryHealthPercent`) and tightened others (variant
 * `images` must now be absolute R2 URLs, not `/public` paths), so validating
 * this snapshot against today's schemas would fail on rows that were perfectly
 * valid when they were written. The seed maps it to database columns directly
 * and lets Postgres be the check.
 *
 * Localized {ar,fr,en} objects were collapsed to their Arabic string when the
 * catalogue moved to single-language content: those columns are plain text
 * now, so seeding an object would write a JSON blob into a text field.
 *
 * Recovered from the pre-deletion backup of the original `content/products.ts`
 * — note that file's Modern Standard Arabic copy was never committed (the
 * rewrite and the deletion landed in the same commit), so this snapshot is the
 * only surviving copy of that text. Do not regenerate it from git history:
 * `a86671e^` still holds the older Darija wording.
 */

export const PRODUCTS_SEED_DATA = [
  /* ------------------------------------------------------------------ iPhone */
  {
    slug: 'iphone-16-pro',
    brand: 'Apple',
    category: 'iphone',
    badges: ['new', 'bestseller'],
    featured: true,
    bestseller: true,
    name: 'آيفون 16 برو',
    description: 'التيتانيوم، ومعالج A18 Pro، وكاميرا 48 ميغابيكسل تصوّر بجودة سينمائية. إنه الآيفون الذي كنت تنتظره.',
    highlights: [
      {
        value: '48',
        unit: 'MP',
        label: 'الكاميرا الرئيسية',
      },
      { value: 'A18', unit: 'Pro', label: 'المعالج' },
      {
        value: '12',
        unit: 'MP',
        label: 'كاميرا السيلفي',
      },
      {
        value: '3',
        unit: null,
        label: 'عدسات خلفية',
      },
    ],
    specs: [
      {
        key: 'screen',
        label: 'الشاشة',
        value: '6.3" ProMotion 120 Hz',
      },
      { key: 'chip', label: 'المعالج', value: 'A18 Pro' },
      {
        key: 'camera',
        label: 'الكاميرا',
        value: '48 MP + 48 MP + 12 MP',
      },
      {
        key: 'battery',
        label: 'البطارية',
        value: '27 h',
      },
      { key: 'sim', label: 'الشريحة', value: 'Nano-SIM + eSIM' },
    ],
    variants: [
      {
        id: 'iphone-16-pro-desert-256',
        colour: {
          slug: 'desert-titanium',
          hex: '#BFA48F',
          label: 'تيتانيوم صحراوي',
        },
        storage: '256 GB',
        price: 289000,
        compareAt: 305000,
        stock: 'in-stock',
        images: ['/products/iphone-16-pro.png'],
      },
      {
        id: 'iphone-16-pro-natural-256',
        colour: {
          slug: 'natural-titanium',
          hex: '#C2BCB2',
          label: 'تيتانيوم طبيعي',
        },
        storage: '256 GB',
        price: 289000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/iphone-16-pro.png'],
      },
      {
        id: 'iphone-16-pro-black-512',
        colour: {
          slug: 'black-titanium',
          hex: '#3B3B3D',
          label: 'تيتانيوم أسود',
        },
        storage: '512 GB',
        price: 329000,
        compareAt: null,
        stock: 'low-stock',
        images: ['/products/iphone-16-pro.png'],
      },
      {
        id: 'iphone-16-pro-white-256',
        colour: {
          slug: 'white-titanium',
          hex: '#F2F1ED',
          label: 'تيتانيوم أبيض',
        },
        storage: '256 GB',
        price: 289000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/iphone-16-pro.png'],
      },
    ],
  },
  {
    slug: 'iphone-16-pro-max',
    brand: 'Apple',
    category: 'iphone',
    badges: ['new'],
    featured: false,
    bestseller: true,
    name: 'آيفون 16 برو ماكس',
    description: 'أكبر شاشة وأطول عمر بطارية في تاريخ آيفون. إذا كنت تصوّر أو تلعب كثيراً، فهذا هو خيارك.',
    highlights: [],
    specs: [
      {
        key: 'screen',
        label: 'الشاشة',
        value: '6.9" ProMotion 120 Hz',
      },
      { key: 'chip', label: 'المعالج', value: 'A18 Pro' },
      { key: 'battery', label: 'البطارية', value: '33 h' },
    ],
    variants: [
      {
        id: 'iphone-16-pro-max-desert-256',
        colour: {
          slug: 'desert-titanium',
          hex: '#BFA48F',
          label: 'تيتانيوم صحراوي',
        },
        storage: '256 GB',
        price: 339000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'iphone-16-pro-max-black-512',
        colour: {
          slug: 'black-titanium',
          hex: '#3B3B3D',
          label: 'تيتانيوم أسود',
        },
        storage: '512 GB',
        price: 379000,
        compareAt: null,
        stock: 'low-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'iphone-16',
    brand: 'Apple',
    category: 'iphone',
    badges: ['bestseller'],
    featured: false,
    bestseller: true,
    name: 'آيفون 16',
    description: 'زر التحكم بالكاميرا، ومعالج A18، وألوان جديدة. أفضل آيفون من حيث السعر.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.1" OLED' },
      { key: 'chip', label: 'المعالج', value: 'A18' },
      {
        key: 'camera',
        label: 'الكاميرا',
        value: '48 MP + 12 MP',
      },
    ],
    variants: [
      {
        id: 'iphone-16-ultramarine-128',
        colour: {
          slug: 'ultramarine',
          hex: '#4C6EA8',
          label: 'أزرق بحري',
        },
        storage: '128 GB',
        price: 219000,
        compareAt: 232000,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'iphone-16-teal-256',
        colour: {
          slug: 'teal',
          hex: '#A8C8C0',
          label: 'أزرق مخضر',
        },
        storage: '256 GB',
        price: 245000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'iphone-16-black-128',
        colour: {
          slug: 'black',
          hex: '#35363A',
          label: 'أسود',
        },
        storage: '128 GB',
        price: 219000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'iphone-15',
    brand: 'Apple',
    category: 'iphone',
    badges: ['promo'],
    featured: false,
    bestseller: false,
    name: 'آيفون 15',
    description: 'الجزيرة الديناميكية وكاميرا 48 ميغابيكسل، بسعر أصبح معقولاً جداً.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.1" OLED' },
      { key: 'chip', label: 'المعالج', value: 'A16 Bionic' },
    ],
    variants: [
      {
        id: 'iphone-15-blue-128',
        colour: {
          slug: 'blue',
          hex: '#D3E0E4',
          label: 'أزرق فاتح',
        },
        storage: '128 GB',
        price: 178000,
        compareAt: 195000,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'iphone-15-black-128',
        colour: {
          slug: 'black',
          hex: '#35363A',
          label: 'أسود',
        },
        storage: '128 GB',
        price: 178000,
        compareAt: 195000,
        stock: 'low-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'iphone-13',
    brand: 'Apple',
    category: 'iphone',
    badges: ['promo'],
    featured: false,
    bestseller: false,
    name: 'آيفون 13',
    description: 'لا يزال قوياً، ولا يزال يستقبل التحديثات، وأصبح سعره في المتناول. مدخل مثالي إلى عالم آبل.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.1" OLED' },
      { key: 'chip', label: 'المعالج', value: 'A15 Bionic' },
    ],
    variants: [
      {
        id: 'iphone-13-midnight-128',
        colour: {
          slug: 'midnight',
          hex: '#25282C',
          label: 'أسود منتصف الليل',
        },
        storage: '128 GB',
        price: 128000,
        compareAt: 142000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },

  /* ----------------------------------------------------------------- Samsung */
  {
    slug: 'galaxy-z-fold-8',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['new'],
    featured: false,
    bestseller: true,
    name: 'غالاكسي Z فولد 8',
    description: 'هاتف وجهاز لوحي في آن واحد. عند فتحه تجد شاشة بحجم 7.6 بوصة تعمل عليها كما لو كانت حاسوباً محمولاً.',
    highlights: [],
    specs: [
      {
        key: 'screen',
        label: 'الشاشة الداخلية',
        value: '7.6" 120 Hz',
      },
      {
        key: 'cover',
        label: 'الشاشة الخارجية',
        value: '6.3" 120 Hz',
      },
      { key: 'ram', label: 'الذاكرة', value: '12 GB RAM' },
    ],
    variants: [
      {
        id: 'galaxy-z-fold-8-silver-256',
        colour: {
          slug: 'silver-shadow',
          hex: '#B8BABE',
          label: 'فضي',
        },
        storage: '256 GB',
        price: 425000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/galaxy-z-fold-8.png'],
      },
      {
        id: 'galaxy-z-fold-8-navy-512',
        colour: {
          slug: 'navy',
          hex: '#2C3A52',
          label: 'كحلي',
        },
        storage: '512 GB',
        price: 468000,
        compareAt: null,
        stock: 'low-stock',
        images: ['/products/galaxy-z-fold-8.png'],
      },
    ],
  },
  {
    slug: 'galaxy-z-fold-8-ultra',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['new', 'last-units'],
    featured: false,
    bestseller: false,
    name: 'غالاكسي Z فولد 8 ألترا',
    description: 'النسخة الكبيرة: كاميرا 200 ميغابيكسل وقلم S Pen داخل الجهاز. أقوى قابل للطي في السوق.',
    highlights: [],
    specs: [
      {
        key: 'screen',
        label: 'الشاشة الداخلية',
        value: '8.0" 120 Hz',
      },
      {
        key: 'camera',
        label: 'الكاميرا',
        value: '200 MP',
      },
      { key: 'pen', label: 'القلم', value: 'S Pen' },
    ],
    variants: [
      {
        id: 'galaxy-z-fold-8-ultra-titanium-512',
        colour: {
          slug: 'titanium-black',
          hex: '#43454A',
          label: 'تيتانيوم أسود',
        },
        storage: '512 GB',
        price: 498000,
        compareAt: null,
        stock: 'low-stock',
        images: ['/products/galaxy-z-fold-8-ultra.png'],
      },
    ],
  },
  {
    slug: 'galaxy-z-flip-8',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['bestseller'],
    featured: false,
    bestseller: true,
    name: 'غالاكسي Z فليب 8',
    description: 'ينطوي ويدخل جيبك من دون أن تشعر بثقله، وتتيح لك الشاشة الخارجية التقاط صور سيلفي بالكاميرا الرئيسية.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.7" 120 Hz' },
      {
        key: 'cover',
        label: 'الشاشة الخارجية',
        value: '3.4"',
      },
      { key: 'battery', label: 'البطارية', value: '4000 mAh' },
    ],
    variants: [
      {
        id: 'galaxy-z-flip-8-blue-256',
        colour: {
          slug: 'blue',
          hex: '#4A6FA5',
          label: 'أزرق',
        },
        storage: '256 GB',
        price: 235000,
        compareAt: 249000,
        stock: 'in-stock',
        images: ['/products/galaxy-z-flip-8.png'],
      },
      {
        id: 'galaxy-z-flip-8-coral-256',
        colour: {
          slug: 'coral-red',
          hex: '#D9584E',
          label: 'أحمر مرجاني',
        },
        storage: '256 GB',
        price: 235000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/galaxy-z-flip-8.png'],
      },
      {
        id: 'galaxy-z-flip-8-mint-512',
        colour: {
          slug: 'mint',
          hex: '#B7CFC0',
          label: 'أخضر نعناعي',
        },
        storage: '512 GB',
        price: 268000,
        compareAt: null,
        stock: 'low-stock',
        images: ['/products/galaxy-z-flip-8.png'],
      },
    ],
  },
  {
    slug: 'galaxy-s25-ultra',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['bestseller'],
    featured: false,
    bestseller: true,
    name: 'غالاكسي S25 ألترا',
    description: 'كاميرا 200 ميغابيكسل وزوم 100x، وقلم S Pen. تجربة أندرويد كاملة دون أي نقص.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.9" 120 Hz' },
      { key: 'camera', label: 'الكاميرا', value: '200 MP' },
      { key: 'zoom', label: 'الزوم', value: '100x' },
    ],
    variants: [
      {
        id: 'galaxy-s25-ultra-black-256',
        colour: {
          slug: 'titanium-black',
          hex: '#43454A',
          label: 'تيتانيوم أسود',
        },
        storage: '256 GB',
        price: 355000,
        compareAt: 372000,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'galaxy-s25-ultra-gray-512',
        colour: {
          slug: 'titanium-gray',
          hex: '#8E9095',
          label: 'تيتانيوم رمادي',
        },
        storage: '512 GB',
        price: 392000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'galaxy-watch-ultra-2',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['new'],
    featured: false,
    bestseller: false,
    name: 'غالاكسي ووتش ألترا 2',
    description: 'هيكل تيتانيوم، مقاومة للماء 100 متر، وبطارية توصل 100 ساعة. مصنوعة للرياضة الحقيقية.',
    highlights: [],
    specs: [
      { key: 'case', label: 'الهيكل', value: '47 mm Titanium' },
      { key: 'battery', label: 'البطارية', value: '100 h' },
      { key: 'water', label: 'مقاومة الماء', value: '10 ATM' },
    ],
    variants: [
      {
        id: 'galaxy-watch-ultra-2-gray-47',
        colour: {
          slug: 'titanium-gray',
          hex: '#7D7F84',
          label: 'تيتانيوم رمادي',
        },
        storage: '47 mm',
        price: 86000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/galaxy-watch-ultra-2.png'],
      },
      {
        id: 'galaxy-watch-ultra-2-white-47',
        colour: {
          slug: 'titanium-white',
          hex: '#E3E2DE',
          label: 'تيتانيوم أبيض',
        },
        storage: '47 mm',
        price: 86000,
        compareAt: null,
        stock: 'low-stock',
        images: ['/products/galaxy-watch-ultra-2.png'],
      },
    ],
  },
  {
    slug: 'galaxy-watch-9',
    brand: 'Samsung',
    category: 'samsung',
    badges: ['bestseller'],
    featured: false,
    bestseller: true,
    name: 'غالاكسي ووتش 9',
    description: 'تقيس النبض والنوم وضغط الدم، وتجعل هاتفك يبقى في جيبك. متوافقة مع جميع أجهزة أندرويد.',
    highlights: [],
    specs: [
      { key: 'case', label: 'الهيكل', value: '44 mm' },
      { key: 'battery', label: 'البطارية', value: '40 h' },
      { key: 'health', label: 'الصحة', value: 'ECG + BIA' },
    ],
    variants: [
      {
        id: 'galaxy-watch-9-silver-44',
        colour: {
          slug: 'silver',
          hex: '#C9CBCF',
          label: 'فضي',
        },
        storage: '44 mm',
        price: 52000,
        compareAt: 58000,
        stock: 'in-stock',
        images: ['/products/galaxy-watch-9.png'],
      },
      {
        id: 'galaxy-watch-9-graphite-40',
        colour: {
          slug: 'graphite',
          hex: '#4A4B4F',
          label: 'رمادي غرافيت',
        },
        storage: '40 mm',
        price: 48000,
        compareAt: null,
        stock: 'in-stock',
        images: ['/products/galaxy-watch-9.png'],
      },
    ],
  },
  {
    slug: 'galaxy-a56',
    brand: 'Samsung',
    category: 'samsung',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'غالاكسي A56',
    description: 'سامسونغ بسعر معقول: شاشة AMOLED، وبطارية تدوم يومين كاملين، وست سنوات من التحديثات.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.7" AMOLED' },
      { key: 'battery', label: 'البطارية', value: '5000 mAh' },
    ],
    variants: [
      {
        id: 'galaxy-a56-graphite-256',
        colour: {
          slug: 'graphite',
          hex: '#3F4145',
          label: 'رمادي غرافيت',
        },
        storage: '8 GB / 256 GB',
        price: 68000,
        compareAt: 74000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },

  /* ----------------------------------------------------------------- Android */
  {
    slug: 'redmi-note-13',
    brand: 'Xiaomi',
    category: 'android',
    badges: ['bestseller', 'promo'],
    featured: false,
    bestseller: true,
    name: 'ريدمي نوت 13',
    description: 'الأكثر مبيعاً لدينا، وليس ذلك من دون سبب: كاميرا 108 ميغابيكسل وبطارية تدوم يومين كاملين.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.67" AMOLED' },
      { key: 'camera', label: 'الكاميرا', value: '108 MP' },
      { key: 'battery', label: 'البطارية', value: '5000 mAh' },
    ],
    variants: [
      {
        id: 'redmi-note-13-black-128',
        colour: {
          slug: 'midnight-black',
          hex: '#2A2C31',
          label: 'أسود',
        },
        storage: '8 GB / 128 GB',
        price: 44500,
        compareAt: 49000,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'redmi-note-13-teal-256',
        colour: {
          slug: 'ocean-teal',
          hex: '#2E6D6E',
          label: 'أزرق محيطي',
        },
        storage: '8 GB / 256 GB',
        price: 51000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'redmi-note-14-pro',
    brand: 'Xiaomi',
    category: 'android',
    badges: ['new'],
    featured: false,
    bestseller: false,
    name: 'ريدمي نوت 14 برو',
    description: 'شاشة منحنية، وشحن بقوة 67 واط، ومقاومة IP68 للماء والغبار. أداء الفئة الرائدة بنصف السعر.',
    highlights: [],
    specs: [
      { key: 'screen', label: 'الشاشة', value: '6.67" AMOLED' },
      { key: 'charge', label: 'الشحن', value: '67 W' },
    ],
    variants: [
      {
        id: 'redmi-note-14-pro-purple-256',
        colour: {
          slug: 'lavender',
          hex: '#8A7BB8',
          label: 'بنفسجي',
        },
        storage: '8 GB / 256 GB',
        price: 62000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'poco-x7-pro',
    brand: 'Poco',
    category: 'android',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'بوكو X7 برو',
    description: 'لعشاق الألعاب: معالج Dimensity 8400 وشحن بقوة 90 واط يملأ البطارية خلال 40 دقيقة.',
    highlights: [],
    specs: [
      { key: 'chip', label: 'المعالج', value: 'Dimensity 8400' },
      { key: 'charge', label: 'الشحن', value: '90 W' },
    ],
    variants: [
      {
        id: 'poco-x7-pro-yellow-256',
        colour: {
          slug: 'poco-yellow',
          hex: '#E0B33C',
          label: 'أصفر',
        },
        storage: '8 GB / 256 GB',
        price: 58000,
        compareAt: 63000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'honor-x9c',
    brand: 'Honor',
    category: 'android',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'هونور X9c',
    description: 'شاشة مقاومة للكسر، وبطارية سعة 6600 مللي أمبير. مصمم ليدوم معك سنوات طويلة.',
    highlights: [],
    specs: [
      { key: 'battery', label: 'البطارية', value: '6600 mAh' },
      { key: 'screen', label: 'الشاشة', value: '6.78" AMOLED' },
    ],
    variants: [
      {
        id: 'honor-x9c-black-256',
        colour: {
          slug: 'black',
          hex: '#2C2E33',
          label: 'أسود',
        },
        storage: '8 GB / 256 GB',
        price: 51000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },

  /* ---------------------------------------------------------------- Computers */
  {
    slug: 'macbook-air-m4',
    brand: 'Apple',
    category: 'pc',
    badges: ['new'],
    featured: false,
    bestseller: true,
    name: 'ماكبوك إير M4',
    description: 'خفيف الوزن، بلا مروحة تبريد، وبطارية تكفي ليوم عمل كامل. أفضل حاسوب محمول للطلاب والمصممين.',
    highlights: [],
    specs: [
      { key: 'chip', label: 'المعالج', value: 'Apple M4' },
      { key: 'screen', label: 'الشاشة', value: '13.6" Liquid Retina' },
      { key: 'battery', label: 'البطارية', value: '18 h' },
    ],
    variants: [
      {
        id: 'macbook-air-m4-sky-256',
        colour: {
          slug: 'sky-blue',
          hex: '#B4C4D8',
          label: 'أزرق سماوي',
        },
        storage: '16 GB / 256 GB',
        price: 268000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'macbook-air-m4-midnight-512',
        colour: {
          slug: 'midnight',
          hex: '#2E3641',
          label: 'أسود منتصف الليل',
        },
        storage: '16 GB / 512 GB',
        price: 312000,
        compareAt: null,
        stock: 'low-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'hp-victus-15',
    brand: 'HP',
    category: 'pc',
    badges: ['bestseller'],
    featured: false,
    bestseller: false,
    name: 'HP فيكتوس 15',
    description: 'بطاقة رسومات RTX 4050 وشاشة بمعدل تحديث 144 هرتز، تشغّل جميع الألعاب الحديثة دون أي مشاكل.',
    highlights: [],
    specs: [
      { key: 'gpu', label: 'بطاقة الرسومات', value: 'RTX 4050 6 GB' },
      { key: 'cpu', label: 'المعالج', value: 'Core i5-13420H' },
      { key: 'screen', label: 'الشاشة', value: '15.6" 144 Hz' },
    ],
    variants: [
      {
        id: 'hp-victus-15-black-512',
        colour: {
          slug: 'mica-silver',
          hex: '#54565B',
          label: 'فضي',
        },
        storage: '16 GB / 512 GB',
        price: 165000,
        compareAt: 179000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'lenovo-ideapad-slim-3',
    brand: 'Lenovo',
    category: 'pc',
    badges: ['promo'],
    featured: false,
    bestseller: false,
    name: 'لينوفو آيديا باد سليم 3',
    description: 'للدراسة والعمل المكتبي: معالج Ryzen 5، وشاشة FHD، ووزن خفيف يمكنك حمله إلى الجامعة كل يوم.',
    highlights: [],
    specs: [
      { key: 'cpu', label: 'المعالج', value: 'Ryzen 5 7520U' },
      { key: 'screen', label: 'الشاشة', value: '15.6" FHD' },
    ],
    variants: [
      {
        id: 'lenovo-ideapad-slim-3-grey-512',
        colour: {
          slug: 'arctic-grey',
          hex: '#8C8E92',
          label: 'رمادي',
        },
        storage: '8 GB / 512 GB',
        price: 78000,
        compareAt: 85000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },

  /* ------------------------------------------------------------- Accessories */
  {
    slug: 'airpods-pro-2',
    brand: 'Apple',
    category: 'accessories',
    badges: ['bestseller'],
    featured: false,
    bestseller: true,
    name: 'إيربودز برو 2',
    description: 'إلغاء ضجيج يعزلك تماماً عن ضوضاء الشارع، وشحن عبر USB-C. أفضل سماعات إيربودز لهاتف آيفون.',
    highlights: [],
    specs: [
      { key: 'anc', label: 'إلغاء الضجيج', value: 'Active' },
      { key: 'battery', label: 'البطارية', value: '30 h' },
    ],
    variants: [
      {
        id: 'airpods-pro-2-white',
        colour: {
          slug: 'white',
          hex: '#F5F5F0',
          label: 'أبيض',
        },
        storage: null,
        price: 42000,
        compareAt: 46000,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'galaxy-buds3-pro',
    brand: 'Samsung',
    category: 'accessories',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'غالاكسي بادز 3 برو',
    description: 'صوت Hi-Fi 24 بيت وترجمة فورية مع هواتف غالاكسي. تصميم جديد بالكامل.',
    highlights: [],
    specs: [
      { key: 'audio', label: 'الصوت', value: '24-bit Hi-Fi' },
      { key: 'battery', label: 'البطارية', value: '26 h' },
    ],
    variants: [
      {
        id: 'galaxy-buds3-pro-silver',
        colour: {
          slug: 'silver',
          hex: '#D5D7DB',
          label: 'فضي',
        },
        storage: null,
        price: 33000,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'anker-powerbank-20k',
    brand: 'Anker',
    category: 'accessories',
    badges: ['bestseller'],
    featured: false,
    bestseller: false,
    name: 'باور بانك أنكر 20000 mAh',
    description: 'تشحن هاتف آيفون بالكامل أربع مرات. شحن سريع بقوة 30 واط ومنفذان. أداة ضرورية عند السفر.',
    highlights: [],
    specs: [
      { key: 'capacity', label: 'السعة', value: '20 000 mAh' },
      { key: 'output', label: 'الخرج', value: '30 W USB-C' },
    ],
    variants: [
      {
        id: 'anker-powerbank-20k-black',
        colour: {
          slug: 'black',
          hex: '#2B2C30',
          label: 'أسود',
        },
        storage: null,
        price: 7500,
        compareAt: 8900,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'charger-30w-usbc',
    brand: 'JTECH',
    category: 'accessories',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'شاحن سريع 30 واط USB-C',
    description: 'يشحن هاتف آيفون بنسبة 50٪ خلال نصف ساعة. يعمل مع آيفون وسامسونغ وكل جهاز يدعم USB-C.',
    highlights: [],
    specs: [
      { key: 'output', label: 'القدرة', value: '30 W PD' },
    ],
    variants: [
      {
        id: 'charger-30w-usbc-white',
        colour: {
          slug: 'white',
          hex: '#F5F5F0',
          label: 'أبيض',
        },
        storage: null,
        price: 4200,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'screen-protector-glass',
    brand: 'JTECH',
    category: 'accessories',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'حماية شاشة زجاج مقوّى',
    description: 'نقوم بتركيبها في المتجر دون فقاعات، وإذا تعرّضت للكسر خلال الأسبوع الأول نستبدلها مجاناً.',
    highlights: [],
    specs: [
      { key: 'hardness', label: 'الصلابة', value: '9H' },
    ],
    variants: [
      {
        id: 'screen-protector-glass-clear',
        colour: {
          slug: 'clear',
          hex: '#E8E8ED',
          label: 'شفاف',
        },
        storage: null,
        price: 1500,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'silicone-case',
    brand: 'JTECH',
    category: 'accessories',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'كفر سيليكون بحماية الزوايا',
    description: 'سيليكون ناعم من الداخل وزوايا مقوّاة. متوفرة لجميع طرازات آيفون وسامسونغ.',
    highlights: [],
    specs: [
      { key: 'material', label: 'المادة', value: 'Silicone + TPU' },
    ],
    variants: [
      {
        id: 'silicone-case-black',
        colour: {
          slug: 'black',
          hex: '#2B2C30',
          label: 'أسود',
        },
        storage: null,
        price: 3500,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
      {
        id: 'silicone-case-sand',
        colour: {
          slug: 'sand',
          hex: '#D8C8B4',
          label: 'بيج',
        },
        storage: null,
        price: 3500,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
  {
    slug: 'braided-usbc-cable',
    brand: 'JTECH',
    category: 'accessories',
    badges: [],
    featured: false,
    bestseller: false,
    name: 'كابل USB-C مضفّر 2 متر',
    description: 'مضفّر لمنع التلف عند نقطة التوصيل، وطويل بما يكفي للشحن وأنت مستلقٍ.',
    highlights: [],
    specs: [
      { key: 'length', label: 'الطول', value: '2 m' },
      { key: 'speed', label: 'السرعة', value: '60 W / 480 Mbps' },
    ],
    variants: [
      {
        id: 'braided-usbc-cable-grey',
        colour: {
          slug: 'grey',
          hex: '#6E6E73',
          label: 'رمادي',
        },
        storage: null,
        price: 1900,
        compareAt: null,
        stock: 'in-stock',
        images: [],
      },
    ],
  },
] as const;
